' Combined VBScript Test Script
' Tests various patterns that may fail in Wine VBScript parser
' Generated by test_vbscript_patterns.py

Option Explicit

' Global test counter
Dim g_testsPassed, g_testsFailed
g_testsPassed = 0
g_testsFailed = 0

Sub ReportTest(testName, passed)
    If passed Then
        g_testsPassed = g_testsPassed + 1
        ' Debug.Print "PASS: " & testName
    Else
        g_testsFailed = g_testsFailed + 1
        Debug.Print "FAIL: " & testName
    End If
End Sub

' ==============================================================
' TEST 1: Basic single-line If with simple assignment
' ==============================================================
Sub Test_BasicSingleLineIf()
    Dim x
    x = 0
    If True Then x = 1
    ReportTest "BasicSingleLineIf", (x = 1)
End Sub

' ==============================================================
' TEST 2: Single-line If with array access on RHS
' ==============================================================
Sub Test_SingleLineIfArrayRHS()
    Dim arr(2)
    arr(0) = 42
    arr(1) = 99
    Dim x
    x = 0
    If True Then x = arr(0)
    ReportTest "SingleLineIfArrayRHS", (x = 42)
End Sub

' ==============================================================
' TEST 3: Consecutive single-line If with array access
' ==============================================================
Sub Test_ConsecutiveSingleLineIfArray()
    Dim arr(2)
    arr(0) = 10
    arr(1) = 20
    Dim x, y
    x = 0
    y = 0
    If True Then x = arr(0)
    If True Then y = arr(1)
    ReportTest "ConsecutiveSingleLineIfArray", (x = 10 And y = 20)
End Sub

' ==============================================================
' TEST 4: Single-line If with member expression and array RHS
' ==============================================================
Class TestBall
    Public Velx
    Public Vely
End Class

Sub Test_MemberExpressionArrayRHS()
    Dim RotVxVy(2)
    RotVxVy(0) = 1.5
    RotVxVy(1) = 2.5

    Dim ball
    Set ball = New TestBall
    ball.Velx = 0
    ball.Vely = 0

    Dim Enabled
    Enabled = True

    If Enabled Then ball.Velx = RotVxVy(0)
    If Enabled Then ball.Vely = RotVxVy(1)

    ReportTest "MemberExpressionArrayRHS", (ball.Velx = 1.5 And ball.Vely = 2.5)
End Sub

' ==============================================================
' TEST 5: Nested single-line If inside multi-line If
' ==============================================================
Sub Test_NestedSingleLineIf()
    Dim arr(2)
    arr(0) = 100
    arr(1) = 200
    Dim x, y
    x = 0
    y = 0

    If True Then
        If True Then x = arr(0)
        If True Then y = arr(1)
    End If

    ReportTest "NestedSingleLineIf", (x = 100 And y = 200)
End Sub

' ==============================================================
' TEST 6: If-Then-Else single line with array
' ==============================================================
Sub Test_IfThenElseArray()
    Dim arr(2)
    arr(0) = 50
    arr(1) = 60
    Dim x
    If True Then x = arr(0) Else x = arr(1)
    ReportTest "IfThenElseArray", (x = 50)
End Sub

' ==============================================================
' TEST 7: The exact VPX FlipperPolarity pattern
' ==============================================================
Class FlipperPolarityTest
    Private m_Enabled

    Public Sub Init()
        m_Enabled = True
    End Sub

    Public Sub ProcessBall(aBall)
        Dim Angle, RotVxVy(2)
        Angle = 45
        RotVxVy(0) = 1.0
        RotVxVy(1) = 2.0

        If m_Enabled Then aBall.Velx = RotVxVy(0)
        If m_Enabled Then aBall.Vely = RotVxVy(1)
    End Sub
End Class

Sub Test_VPXFlipperPolarity()
    Dim fp
    Set fp = New FlipperPolarityTest
    fp.Init

    Dim ball
    Set ball = New TestBall
    ball.Velx = 0
    ball.Vely = 0

    fp.ProcessBall ball

    ReportTest "VPXFlipperPolarity", (ball.Velx = 1.0 And ball.Vely = 2.0)
End Sub

' ==============================================================
' RUN ALL TESTS
' ==============================================================
Sub RunAllTests()
    Test_BasicSingleLineIf
    Test_SingleLineIfArrayRHS
    Test_ConsecutiveSingleLineIfArray
    Test_MemberExpressionArrayRHS
    Test_NestedSingleLineIf
    Test_IfThenElseArray
    Test_VPXFlipperPolarity

    Debug.Print "================================"
    Debug.Print "Tests Passed: " & g_testsPassed
    Debug.Print "Tests Failed: " & g_testsFailed
    Debug.Print "================================"
End Sub

' Run tests when script loads
RunAllTests
